### ISSUE TITLE
AttributeError in __init__ due to ctypes.wintypes missing import

### ISSUE THREAD

**Issue by strictlymike** [fireeye/flare-qdb#22]
The file `__init__.py` should import `ctypes.wintypes` at the top to allow the following line (and friends) to work:

```
('SizeOfStruct', ctypes.wintypes.ULONG),  # 1104
```

Currently just running `flareqdb.exe` elicits:

```
AttributeError: 'module' object has no attribute 'wintypes'
```

**Comment by strictlymike** [comment]
Completed with commit fdad21e

**Comment by strictlymike** [comment]
Thanks to @schrodyn for making me get off my butt and close this btw :-P

**Comment by schrodyn** [comment]
Beautiful, the author and the code. Thanks @strictlymike 

For anyone in the future - this affected the version of flare-qdb currently in FlareVM but is now fixed.
